[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "npm install --prefix client",
  "npm run build --prefix client"
]

[start]
cmd = "gunicorn --chdir server --log-level debug app:app"

[dependencies]
# Add dependencies for Python, Node.js, PostgreSQL, etc.
packages = [
  "python38",  # Specify the Python version
  "pipenv",    # Python dependency manager
  "postgresql_16", # PostgreSQL database
  "nodejs",    # Node.js runtime
]
