[phases.install]
commands = [
  "pip install -r requirements.txt",
  "npm install --prefix client"
]

[phases.build]
commands = [
  "npm run build --prefix client"
]

[start]
commands = [
  "gunicorn --chdir server --log-level debug app:app"
]